Closes #23 - Added parser for word and pdf
intelligentnode/IntelliServer pull request #40
Opened 2023-09-19 14:21 UTC by pushoo-sharma

Closes #23 - Added parser for word and pdf

2023-09-20 12:45 UTC, intelligentnode requested changes

2023-09-20 12:45 UTC, intelligentnode commented on intelliserver/api/parser/index.js
> +            const text = data.text;
Return the text of each page in a dictionary.

The response should match the below format
```
{
  "status": "success",
  "data": {
        "total_pages": 5,    
        "pages": [
		{
                "page_number": 1,
                "text": "This is the text content of the first page"
                },
                {
                "page_number": 2,
                "text": "This is the text content of the second page"
                },
                ....
      ]
  }
}
```

2023-09-20 12:45 UTC, intelligentnode commented on intelliserver/api/parser/index.js
> +            const text = result.value;
The same comment applies here, however word parser return paragraphs instead of pages.

2023-09-20 17:23 UTC, pushoo-sharma commented
@intelligentnode I have made the changes, you may review this. Also added Postman collection for it

2023-09-25 07:40 UTC, Barqawiz approved these changes

2023-09-25 07:42 UTC, merged